config/routes.rb
ToDoList::Application.routes.draw do
  devise_for :users
  get 'profile',  to: "persons#profile"
  get 'sql',      to: "pages#sql"

  resources :tasks
  resources :projects

  post 'tasks/editTaskStatus',      to: 'tasks#editTaskStatus'#, as: 'editTaskStatus' 
  post 'projects/editProjectName',  to: 'projects#editProjectName'
  post 'tasks/editTaskName',        to: 'tasks#editTaskName'
  post 'tasks/setDeadline/',        to: 'tasks#setDeadline'
  post 'tasks/swapTasks',           to: 'tasks#swapTasks'
  
  match '/todolist', to: 'pages#todolist', via: 'get'

  root 'pages#todolist'
  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user
	has_many :tasks, dependent: :destroy
	validates :name, :user_id,
			 presence: true, #не пустая строка
			 #uniqueness: true, 
			 length: { maximum: 50 }
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :project
	validates :name, :project_id,
			 presence: true, #не пустая строка
			 length: { maximum: 200 }

	#def left_days
	#  if (task.deadline && !task.status)
	#    write_attribute :left_days, "left "+(task.deadline.to_date - Time.now.to_date).to_i.to_s + " day".pluralize((task.deadline.to_date - Time.now.to_date).to_i)
	#  end 
	#end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
  		 :registerable,
         :recoverable, 
         :rememberable,
         :trackable, 
         :validatable

  has_many :projects, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  before_action :authenticate_user! #, except => [:show, :index]
  
  protect_from_forgery with: :exception

  rescue_from ActionController::RoutingError do |exception|
 	logger.error 'Routing error occurred'
 	render plain: '404 Not found', status: 404 
  end
  
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def error404
    render status: :not_found
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def todolist
  	@project = Project.new
    @task = Task.new

  	@user_id = current_user.id #used in project/_rorm.html.erb
  	@projects = Project.where(user_id: @user_id).order(created_at: :desc) #current user projects
  	@tasks = Task.where(project_id: @projects).order(rating: :desc) #cut down extra projects, list only for current user`s tasks

  end

end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
  	@info = User.find_by(email: current_user.email)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [ :destroy, :editProjectName ] #:show, :edit, :update

  # POST /projects
  def create
    @project = Project.new(project_params) 
    @task = Task.new

    respond_to do |format|
      if @project.save
        format.html { render :partial => "projects/show_project", :locals => { :project => @project } } 
        #format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render html: "Error, can not save... reload page and try again" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { head :no_content } 
      #format.json { head :no_content }
    end
  end

  def editProjectName
    if have_access(@project) then 
      @project.update(project_params)
    else 
      flash[:warning] = "Something went wrong, try again. Can not find project by given id or you have no permission"
      #render html: 'can not find project by given id or you have no permission'
    end
  end

  private
    def have_access(project)
     return true if project  && (project.user_id == current_user.id)  
     false   
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_project
         @project = Project.find(params[:id] || params[:project][:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :user_id)
    end
end

# GET /projects
  #def index
  #  @user_id = User.find_by(email: current_user.email).id
  #  @projects = Project.where(user_id: @user_id)
  #  @tasks = Task.where(project_id: @projects) #cut down extra projects, list only current user tasks
  #end

  # GET /projects/1
  #def show
  #end

  # GET /projects/new
  #def new
  #  @project = Project.new
    #@user_id = User.find_by(email: current_user.email).id
  #end

  # GET /projects/1/edit
  #def edit
    #@user_id = User.find_by(email: current_user.email).id
  #end

  # PATCH/PUT /projects/1
  #def update
  #  respond_to do |format|
  #    if @project.update(project_params)
  #      format.html { redirect_to todolist_url, notice: 'Project was successfully updated.' }
  #      format.json { head :no_content }
  #    else
  #     format.html { render action: 'edit' }
  #      format.json { render json: @project.errors, status: :unprocessable_entity }
  #   end
  # end
  #end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:destroy, :editTaskName, :editTaskStatus, :setDeadline] #:show, :edit, :update,

  # POST /tasks
  def create
    @task = Task.new(task_params) 
    #@projects = Project.where(user_id: current_user.id) #current user projects
    #@tasks = Task.where(project_id: @projects)
    respond_to do |format|
      if @task.save
        format.html { render :partial => "tasks/form_for_filling_project_by_one_task", :locals => { :task => @task } } 
      else
        format.html { head :no_content }
      end
    end
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { head :no_content }
    end
  end

  def editTaskStatus
    @task.update(task_params)
  end 

  def editTaskName
    @task.update(task_params)
  end

  def setDeadline
    @task.update(task_params)
  end

  def swapTasks
    rating_one = Task.find_by(id: params[:id_one]).rating
    rating_two = Task.find_by(id: params[:id_two]).rating
    
    Task.find_by(id: params[:id_one]).update(rating: rating_two)
    Task.find_by(id: params[:id_two]).update(rating: rating_one)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id] || params[:task][:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:rating, :name, :status, :project_id, :value, :deadline)
    end
end


  # GET /tasks
  # GET /tasks.json
  #def index
  #  @projects = Project.where(user_id: User.find_by(email: current_user.email).id) #current user projects

  #  @tasks = Task.where(project_id: @projects)
    
  #end

  # GET /tasks/1
  # GET /tasks/1.json
  #def show
  #end

  # GET /tasks/new
  #def new
  #  @task = Task.new
  #end

  # GET /tasks/1/edit
  #def edit
  #end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  #def update
  #  respond_to do |format|
  #    if @task.update(task_params)
  #      format.html { redirect_to @task, notice: 'Task was successfully updated.' }
  #      format.json { head :no_content }
  #    else
  #      format.html { render action: 'edit' }
  #      format.json { render json: @task.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "ToDoList"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    for PrivatBank <a target="_blank" href="https://join.skype.com/invite/arGIny0G6Mov"> by Oleksii Yesin</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
    <header>
      <nav class="navbar navbar-default">
        <div class="container-fluid">

          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "TODO LISTS", root_path, class: "navbar-brand" %>
          </div>
       
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <% if user_signed_in? %>
            <ul class="nav navbar-nav">
              <li><%= link_to content_tag(:span, "(current)", class: "sr-only"), sql_path %></li>
            </ul>
            <ul class="navbar-form navbar-left">
                <span class="welcome"> Welcome: <%= current_user.email %></span>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "go to SQL Task", sql_path %></li>
                  <li><%= link_to "about user", profile_path %></li>
                  <li><%= link_to "ToDo lists", root_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to  "Exit", destroy_user_session_path, :method => :delete %></li>
                </ul>
              </li>
              <li><%= link_to  content_tag(:span, '', class: "glyphicon glyphicon-log-out"), destroy_user_session_path, :method => :delete %></li>
            </ul>
            <% else %>
              <ul class="nav navbar-nav navbar-right">
                <li><%= link_to 'Login', new_user_session_path %></li>
                <li><%= link_to 'Sign Up', new_user_registration_path %></li> 
              </ul>
            <% end %>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>  
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<%= favicon_link_tag 'favicon.ico' %>
	<title><%= full_title(yield(:title)) %></title>
	<%= stylesheet_link_tag    "application", media: "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
  </head>

  <body>
	<%= render 'layouts/header' %>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	<div class="content">		
	  <div class="target_for_project">
		  <%= yield %>		
	  </div>

	  <%= image_tag("ajax-loader.gif", :alt => "loader", class: "ajax_loader") %>
	  <div class="row">
		<%= render 'layouts/footer' %>
	  </div>
	</div>
  </body>
</html>

app/views/pages/_modal.html.erb
  <!-- Modal -->
  <div class="modal fade" id="modal_add_project" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h4 class="modal-title">Please enter the name of the project</h4>
        </div>
        <div class="modal-body">
          <%= render 'projects/form' %>     
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

app/views/pages/sql.html.erb
<% provide(:title, 'SQL') %>
<div class="sql_header">
	<h2>SQL task</h2>	
</div>

<div class="transparent_sql">
	<h5>Given tables:</h5>
	<ul class="db_tables">
		<li>★ tasks (id, name, status, project_id, rating, deadline)</li>
		<li>★ projects (id, name, user_id)</li>
	</ul>
	<h5>Write the queries for:</h5>
	<ul class="list_of_sql_tasks">
		<li>get all statuses, not repaeting, alphabeticaly ordered
			<ul>
				<li> SELECT DISTINCT status FROM tasks ORDER BY status ASC</li>
				<!-- <li> Task.select(:status).uniq.order(status: :asc)</li> -->
			</ul>
		</li>
		<li>get the count of all tasks in each project, order by tasks count descending
			<ul> 
				<li>SELECT project_id, COUNT(*) AS count_all 
					FROM tasks 
					GROUP BY project_id 
					ORDER BY count_all DESC</li>
			</ul>
		</li>
		<li>get the count of all tasks in each project, order by projects names
			<ul>
				<li>SELECT COUNT(tasks.id) AS amoun_of_tasks, projects.name AS project_name 
					FROM projects LEFT JOIN tasks 
					ON tasks.project_id = projects.id
					GROUP BY project_id 
					ORDER BY projects.name
				</li>
			</ul>
		</li>
		<li>get the tasks for all projects having the name beginning with “N” letter
			<ul>
				<li>SELECT tasks.name AS task_name, projects.name AS project_name
					FROM projects LEFT JOIN tasks 
					ON projects.id = tasks.project_id
					WHERE tasks.name LIKE "N%"
				</li>
			</ul>
		</li>
		<li>get the list of all projects containing the ‘a’ letter in the middle of the name, and show the tasks count near each project. Mention that there can exist projects without tasks and tasks with project_id=NULL
			<ul>
				<li>SELECT projects.name AS project_name, COUNT(tasks.id) AS amount_of_tasks
					FROM projects LEFT JOIN tasks
					ON projects.id = tasks.project_id
					WHERE projects.name LIKE "%a%"
					GROUP BY tasks.project_id
				</li>
			</ul>
		</li>
		<li>get the list of tasks with duplicate names. Order alphabetically
			<ul>
				<li>SELECT COUNT(name) AS amount_of_duplicated_name, name
					FROM tasks
					GROUP BY name 
					HAVING amount_of_duplicated_name > 1
					ORDER BY name ASC
				</li>
			</ul>
		</li>
		<li>get the list of tasks having several exact matches of both name and status, from the project ‘Garage’. Order by matches count
			<ul>
				<li>SELECT tasks.name, COUNT(tasks.name) AS amount_of_tasks
					FROM projects INNER JOIN tasks
					ON projects.id = tasks.project_id
					WHERE projects.name = 'Garage'
					GROUP BY tasks.name, tasks.status
					HAVING amount_of_tasks > 1
				</li>
			</ul>
		</li>
		<li>get the list of project names having more than 10 tasks in status ‘completed’. Order by project_id
			<ul>
				<li>SELECT projects.name, COUNT(tasks.id) AS amount_of_tasks
					FROM projects INNER JOIN tasks
					ON projects.id = tasks.project_id
					WHERE tasks.status = 't'
					GROUP BY tasks.project_id
					HAVING amount_of_tasks > 10
					ORDER BY tasks.project_id ASC
 				</li>
			</ul>
		</li>
		
	</ul>
</div>

app/views/pages/todolist.html.erb
    <% provide(:title, 'Home') %>
    <% @projects.each do |project| %>
    <% @project_id = project.id %> <!-- Add Task to direct Project -->
      <table class="table table-hover">
        <thead>
          <tr>
            <th class="control_left_side"><span class="glyphicon glyphicon-hourglass"></span></th>
            <th colspan="5" class="projects project_name" id= <%="project_name_#{project.id}"%> ><%= project.name %></th>
            <th class="control"><span class="glyphicon glyphicon-pencil edit_project_name control_right_side" id = <%= @project_id %> ></span></th>
            <th class="control"><%= link_to '', project, remote: true, class: "glyphicon glyphicon-trash control_right_side", method: :delete, data: { confirm: 'Are you sure?' } %></th>
          </tr>
          <%= render 'tasks/form_for_add_task' %>
        </thead>
        <tbody class="put_task_inside_me">
          <%= render 'tasks/form_for_filling_project_by_tasks' %> 
        </tbody>
      </table>
    <% end %>
    <%= render 'modal' %>
    <a data-toggle="modal" href="#modal_add_project" class="btn btn-primary btn-lg" id="add_project">Create new Project</a>

app/views/persons/profile.html.erb
<% provide(:title, 'Profile') %>

<div class="sql_header">
	<h2>Statistics</h2>	
</div>

<div class="transparent_sql">
	
	<ul class="list_of_sql_tasks">
		
		
		<li>You have been registered at:
			<ul>
				<li> <%= @info.created_at %></li>
			</ul>
		</li>
		<li>Number of visits is:
			<ul>
				<li> <%= @info.sign_in_count %> times </li>
			</ul>
		</li>
		<br><br>
		<li>Last Sign in at: 
			<ul>
				<li> <%= @info.last_sign_in_at %> </li>
			</ul>
		</li>
		<li>Last Sign in from IP:
			<ul>
				<li> <%= @info.last_sign_in_ip %> </li>
			</ul>
		</li>
		<br><br>
		<li>Current Sign in at:
			<ul>
				<li> <%= @info.current_sign_in_at %> </li>
			</ul>
		</li>
		<li>Current Sign in IP:
			<ul>
				<li> <%= @info.current_sign_in_ip %> </li>
			</ul>
		</li>
	</ul>
</div>

app/views/projects/_form.html.erb
      <%= form_for(@project) do |f| %>
        
        <% if @project.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
            <ul><% @project.errors.full_messages.each do |msg| %> <li><%= msg %></li> <% end %></ul>
          </div>
        <% end %>

        <div class="input-group create_new_project">
          <%= f.text_field :name, class: 'form-control', placeholder: 'Start typing here to create a new project...', maxlength: 50, required: true %>
          <%= f.hidden_field :user_id, value: @user_id %>
          <span class="input-group-btn">
            <%= f.submit 'Create', remote: true, class: 'btn btn-success create_new_project_bt' %>
          </span>
        </div>
      <% end %>

app/views/projects/_show_project.html.erb
<% @project_id = project.id %> <!-- Add Task to direct Project -->
<table class="table table-hover">
  <thead>
    <tr>
      <th class="control_left_side"><span class="glyphicon glyphicon-hourglass"></span></th>
      <th colspan="5" class="projects project_name" id= <%="project_name_#{project.id}"%> ><%= project.name %></th>
      <th class="control"><span class="glyphicon glyphicon-pencil edit_project_name control_right_side" id = <%=@project_id %> ></span></th>
      <th class="control"><%= link_to '', project, remote: true, class: "glyphicon glyphicon-trash control_right_side", method: :delete, data: { confirm: 'Are you sure?' } %></th>
    </tr>
  <%= render 'tasks/form_for_add_task' %> 
  </thead>
  <tbody class="put_task_inside_me"> </tbody>
</table>

app/views/tasks/_form_for_add_task.html.erb
      <tr>
        <th class="control_left_side"><span class="glyphicon glyphicon-plus-sign"></span></th>
        <th colspan="7" class="projects">
          <%= form_for(@task) do |f| %>
            <% if @task.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
                <ul> <% @task.errors.full_messages.each do |msg| %><li><%= msg %></li><% end %></ul>
              </div>
            <% end %>

            <span class="input-group add_tast_to_project">
              <%= f.text_field :name, class: 'form-control add_tast_to_project_form', placeholder: 'Start typing here to create a task...', maxlength: 200, required: true %>
              <%= f.hidden_field :project_id, value: @project_id %> <!-- Add Task to direct Project -->
              <%= f.hidden_field :rating, value: Time.now %>
              <span class="input-group-btn">
                <%= f.submit 'Add Task', remote: true, class: 'btn btn-success addTask' %>
              </span>
            </span>
          <% end %>
        </th>
      </tr>

app/views/tasks/_form_for_filling_project_by_one_task.html.erb
		<tr class="forchack" id=<%= 'tr_task_id_'+task.id.to_s %>>
		    <td class="control_left_side"><%= check_box_tag task.id, task.status, task.status, class: 'checked' %></td>  
		    <td class="tasks"><%= task.name %></td>
		    <td class="left_days"></td>      
		    <td class="control calendar"><span class="glyphicon glyphicon-calendar deadline" title= <%= task.deadline ? task.deadline : "Set deadline" %> ></span></td>    
		    <td class="control"><span class="glyphicon glyphicon glyphicon-arrow-up" aria-hidden="true"></span></td>
		    <td class="control"><span class="glyphicon glyphicon glyphicon-arrow-down" aria-hidden="true"></span></td>
		    <td class="control"><span class="glyphicon glyphicon-pencil edit_task_bt" id = <%='bt_edit_id_'+task.id.to_s %>  aria-hidden="true"></span></td>
		    <td class="control"> <%= link_to '', task, remote: true, class: "glyphicon glyphicon-trash", method: :delete, data: { confirm: 'Are you sure?' } %> </td>
		</tr>

app/views/tasks/_form_for_filling_project_by_tasks.html.erb
    <% @sort_tasks = @tasks.where(project_id: @project_id) %>
    <% @sort_tasks.each do |task| %>
      <tr class="forchack" id=<%= 'tr_task_id_'+task.id.to_s %>>
        <td class="control_left_side"><%= check_box_tag task.id, task.status, task.status, class: 'checked' %></td>  
        <td class="tasks"><%= task.name %></td>
            <% if (task.deadline && !task.status)  %>

                <% left_days =  "left "+(task.deadline.to_date - Time.now.to_date).to_i.to_s + " day".pluralize((task.deadline.to_date - Time.now.to_date).to_i) %>
            <% end %>
        <td class="left_days"><%= left_days %></td>    
        <td class="control calendar"><span class="glyphicon glyphicon-calendar deadline" title= <%= task.deadline ? task.deadline : "Set deadline" %> ></span></td>
        
        <td class="control"><span class="glyphicon glyphicon glyphicon-arrow-up" aria-hidden="true"></span></td>
        <td class="control"><span class="glyphicon glyphicon glyphicon-arrow-down" aria-hidden="true"></span></td>
        <td class="control"><span class="glyphicon glyphicon-pencil edit_task_bt" id = <%='bt_edit_id_'+task.id.to_s %>  aria-hidden="true"></span></td>
        <td class="control"> <%= link_to '', task, remote: true, class: "glyphicon glyphicon-trash", method: :delete, data: { confirm: 'Are you sure?' } %> </td>
      </tr>
    <% end %>